plantBUDS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('share.urls')),
    path('admin/', admin.site.urls),
]

share/urls.py
from django.urls import path, include
from . import views  #import everything from views module

app_name = 'share'

urlpatterns = [
    # Most redirects lead here if user has been authenticated
    path('', views.index, name='index'),
    path('', views.info_page, name='info_page'),
    # authentication: signup, login, logout
    path('create', views.create, name='create'),
    path('loguser', views.login_user, name='loguser'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup, name='signup'),

    path('dashboard', views.dashboard, name='dashboard'),
    path('info_page', views.info_page, name='info_page'),
    path('all_posts', views.farmer_posts, name='farmer_posts'),

    path('posts_index/<int:plantbuddy_id>/show', views.show_posts_index, name='show_posts_index'),
    path('posts/<int:plantbuddy_id>/show', views.show_posts, name='show_posts'),

    path('post/<int:plantbuddy_id>/edit', views.edit_post, name='edit_post'),
    path('post/<int:plantbuddy_id>/update', views.update_post, name='update_post'),
    path('post/<int:my_posts_id>/delete', views.delete_post, name='delete_post'),

    path('publish_post', views.publish_post, name='publish_post'),
    path('create_post', views.create_post, name='create_post'),


]

share/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class PlantTip(models.Model):
	def __str__(self):
		return self.title

	tipText = models.CharField(max_length=500)
	tipTitle = models.CharField(max_length=30)

class PlantBuddy(models.Model):
	def __str__(self):
		return self.user.username

	farm_pro = models.BooleanField(default=False)  # the user is not a coder yet
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	created = models.DateField(auto_now=True)   # maybe redundant, user model has date_joined
	updated = models.DateField(auto_now=True)

class Publishing(models.Model):
    def __str__(self):
        return self.title

    plantbuddy = models.ForeignKey(PlantBuddy, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=False, blank=False, unique=False)
    description = models.TextField(max_length=100, null=False, blank=False, unique=False)
    subject = models.CharField(max_length=50, null=False, blank=False, unique=False)
    body = models.TextField(max_length=10000, unique=False)
    make_public = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)     # everytime the obj is saved, new time is saved

share/views.py
# import three functions: authentication, login, logout
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from .models import PlantTip, PlantBuddy, Publishing
from django.contrib.auth.models import User
from django.http import HttpResponse

def index(request):
    # request for user authentication
    if request.method == "GET":
#        if request.user.is_authenticated:
#            user = request.user
            all_posts = Publishing.objects.all()   # all_posts is a list object [   ]

            return render(request, "share/index.html", {"all_posts": all_posts})
#        else:
#            return redirect("share:login")
    else:
        return HttpResponse(status=500)
'''

    else:
        return redirect("share:login")
    else:
        return HttpResponse(status=500)
'''
def dashboard(request):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
        else:
            posts = Publishing.objects.filter(plantbuddy=user.plantbuddy.id)   # Posts table has a plantbuddy field (FK)

            print('*********** Testing objs retrieved from DB ************')
            print('posts:', posts)
            print('*******************************')

            return render(request, "share/dashboard.html", {'posts':posts})

def info_page(request):
    # request for user authentication
    if request.method == "GET":
        return render(request, "share/info_page.html")
    else:
        return redirect("share:login")
'''    else:
        return HttpResponse(status=500)
'''
def signup(request):
    if request.user.is_authenticated:
        return redirect("share:index")
    return render(request, 'share/signup.html')

def create(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        farm_pro = True

        if username is not None and email is not None and password is not None: # checking that they are not None
            if not username or not email or not password: # checking that they are not empty
                return render(request, "share/signup.html", {"error": "Please fill in all required fields"})
            if User.objects.filter(username=username).exists():
                return render(request, "share/signup.html", {"error": "Username already exists"})
            elif User.objects.filter(email=email).exists():
                return render(request, "share/signup.html", {"error": "Email already exists"})
            # save our new user in the User model
            user = User.objects.create_user(username, email, password)
            plantbuddy = PlantBuddy.objects.create(user=user, farm_pro = farm_pro).save()
            user.save()

            login(request, user, backend="django.contrib.auth.backends.ModelBackend")
            # this logs in our new user, backend means that we are using the  Django specific auhentication and not 3rd party

        return redirect("share:index")

    else:
        return redirect("share:signup")

def login_view(request):
    if request.user.is_authenticated:
        return redirect("share:index")
    return render(request, 'share/login.html')

# the function loguser is called from the login form
def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        if not username or not password:
            return render(request, "share/login.html", {"error":"One of the fields was empty"})
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("share:dashboard")
        else:
            return render(request, "share/login.html", {"error":"Wrong username or password"})
    else:
        return redirect("share:index")

def logout_view(request):
    logout(request)
    return redirect("share:index")

def show_posts_index(request, plantbuddy_id):
    if request.method == "GET":
        user = request.user
        # make sure to import the fucntion get_object_or_404 from  django.shortcuts
        posts = get_object_or_404(Publishing, pk=plantbuddy_id)

        # Module 6
        if posts.make_public or posts.plantbuddy.user.id == user.id:
            return render(request, "share/show_posts_index.html", {"user":user, "posts":posts})
        else:
            # the post is private and you are not the author
            return render(request, "share/index.html",
            {"error":"The post you clicked is still private and you are not the author"})


def show_posts(request, plantbuddy_id):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
        else:
            # make sure to import the fucntion get_object_or_404 from  django.shortcuts
            posts = get_object_or_404(Publishing, pk=plantbuddy_id)

            # Module 6
            if posts.make_public or posts.plantbuddy.user.id == user.id:
                return render(request, "share/show_posts.html", {"user":user, "posts":posts})
            else:
                # the post is private and you are not the author
                return render(request, "share/index.html",
                {"error":"The post you clicked is still private and you are not the author"})


def farmer_posts(request):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
        else:
            all_posts = Publishing.objects.filter(plantbuddy=user.plantbuddy.id)   # Posts table has a plantbuddy field (FK)

            print('*********** Testing objs retrieved from DB ************')
            print('all_posts:', all_posts)
            print('*******************************')

            return render(request, "share/farmer_posts.html", {'all_posts':all_posts})

def publish_post(request):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")
        else:
            return render(request, "share/publish_post.html", {"user":user} )

def create_post(request):
    if request.method == "POST":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")

        plantbuddy = user.plantbuddy
        title = request.POST["title"]
        description = request.POST["description"]
        body = request.POST["body"]
        subject = request.POST["subject"]
        make_public = request.POST.get('make_public', False)

        if make_public == 'on':
            make_public = True
        else:
            make_public = False

        if not title and not description and not body:
            return render(request, "share/publish_post.html", {"error":"Please fill in all required fields"})

        try:
            my_posts = Publishing.objects.create(plantbuddy=plantbuddy, title=title, description=description, body=body, subject=subject, make_public=make_public)
            my_posts.save()

            my_posts = get_object_or_404(Publishing, pk=my_posts.id)

            # Fixed the create_post valueError --> changed references to plantbuddy to my_posts
            return render(request, "share/dashboard.html",{"user":user, "my_posts":my_posts})

        except:
            return render(request, "share/publish_post.html", {"error":"Can't create the post"})

    else:
        # the user enteing    http://127.0.0.1:8000/problem/8/create
        user = request.user
        all_posts = Publishing.objects.all()
        return render(request, "share/index.html", {"user":user, "all_posts": all_posts, "error":"Can't create!"})

def edit_post(request, plantbuddy_id):
    if request.method == "GET":
        user = request.user
        if not user.is_authenticated:
            return redirect("share:login")

        plantbuddy = get_object_or_404(Publishing, pk=plantbuddy_id)


        if plantbuddy.plantbuddy.user.id == user.id:
            return render(request, "share/edit_post.html", {"plantbuddy":plantbuddy})
        else:
            return render(request, "share/index.html",
            {"error":"You are not the author of the post that you tried to edit."})

# Module 6
def update_post(request, plantbuddy_id):
    if request.method == "POST":
        user = request.user
        if not user.is_authenticated:
            return HttpResponse(status=500)

        plantbuddy = get_object_or_404(Publishing, pk=plantbuddy_id)

        if not request.POST["title"] or not request.POST["description"] or not request.POST["body"]:
            return render(request, "share/edit_post.html", {"plantbuddy":plantbuddy,
            "error":"One of the required fields was empty"})

        else:
            title = request.POST["title"]
            description = request.POST["description"]
            body = request.POST["body"]

            make_public = request.POST.get('make_public', False)

            print('***********************')
            print('user input make_public:', make_public)    # it shows as on

            if make_public == 'on':
                make_public = True
            else:
                make_public = False

            print('******** Testing *************')
            print('make_public:', make_public)
            print('***********************')

            if plantbuddy.plantbuddy.user.id == user.id and not plantbuddy.make_public:
                Publishing.objects.filter(pk=plantbuddy_id).update(title=title, description=description, body=body, make_public=make_public)
                return redirect("share:farmer_posts")

            else:

share/templates/share/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>plantBUDS</title>
  {% load static %}
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'share/startbootstrap/vendor/bootstrap/css/bootstrap.min.css' %}"/>

  <!-- Custom fonts for this template -->
  <link rel="stylesheet" type="text/css" href="{% static 'share/startbootstrap/css/one-page-wonder.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'share/startbootstrap/css/one-page-wonder.css' %}"/>

  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top" style="background-color: rgba(69,69,69,0.5)">
    <!-- <div class="container"> -->
    <a class="navbar-brand" href="{% url 'share:index' %}"><div class="navText" style="font-size:25px;">plantBUDS</div></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbarContainer collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'share:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'share:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'share:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'share:signup' %}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    <header class="jumbotron my-4" style="height: 300px;background-image: url('/static/share/images/cornfield2.jpg'); background-repeat: no-repeat; background-size:cover;">
      <h1 class="title is-2" style="text-align: center">plantBUDS</h1>
      <p class="lead" style="text-align: center">LEARN MORE ABOUT PLANTS</p>
      <div class="center-wrapper">
        <a href="{% url 'share:info_page' %}" class="button btn-lg">Learn More</a>
      </div>
    </header>
  </div>
  <br>
  <br>
  <br>

  <section>
    {% block content%}
    {% endblock %}
  </section>

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; PlantBuds 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="../static/share/startbootstrap/vendor/jquery/jquery.min.js"></script>
  <script src="../static/share/startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

share/templates/share/dashboard.html
{% extends "share/base.html" %}
{% block content %}
  <!-- Page Content -->
  <div class="postContainer">

    <!-- Jumbotron Header -->
    <header class="jumbotron">
      <h1 class="title is-2"> Hello, <span style="color:#1496ed">{{ user.username }}</span> !</h1>
      <p class="lead">You can publish new posts here:</p>
      <a href="{% url 'share:publish_post' %}" class="button btn-primary btn-sm">Publish a post!</a>
      <br><br><br>
      <p class="lead">Posts created by you:</p>
      <a href="{% url 'share:farmer_posts' %}" class="button btn-primary btn-sm">Show your posts!</a>
      <br><br><br>
    </header>
    <section>
      {% block posts %}
      {% endblock %}
    </section>
  </div>

{% endblock %}

share/templates/share/edit_post.html
{% extends "share/dashboard.html" %}
{% block posts %}
<!DOCTYPE html>
<html>
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  body {font-family: Arial, Helvetica, sans-serif;}
  * {box-sizing: border-box;}

  h3 {
    text-align: center;
  }

  input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
  }

  input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }

  .container {
    border-radius: 5px;
    padding: 20px;
  }
  </style>
</head>

<body>
  <br>
  <h3>Update Post</h3>

  <div class="container">
    {% if error %}
       <h3 style="color: red">{{ error }}</h3>
    {% endif %}

    <form action = "{% url 'share:update_post' plantbuddy.id %}" method="post">
      {% csrf_token %}

      <label for="title">Title</label>
      <input type="text" id="title" name="title" value="{{plantbuddy.title}}">

      <label for="description">Description</label>
      <input type="text" id="description" name="description" value="{{plantbuddy.description}}">

      <label for="body">Body</label>
      <textarea id="body" name="body" style="height:200px">{{plantbuddy.body}}</textarea>

      <label for="subject">Subject</label>
      <select id="subject" name="subject">
        <option value="farming">Farming</option>
        <option value="gardening">Gardening</option>
        <option value="general">General</option>
      </select>

      <label class="checkbox">
          {% if  plantbuddy.make_public %}
            <br>This post is Public!

          {% else %}
            <br>This post is Private! Do you want to make it public?
            <input type="checkbox"  id="make_public" name="make_public" />

          {% endif %}
      </label>



      <div class="field" style="text-align: center;">
        <div class="control">
          <button class="button is-success is-outlined is-fullwidth" type="submit" name="update" value="Update">Update</button>&nbsp;
        </div>
      </div>
    </form>
    <br><br>
    <h3 class="title is-5">Delete Post: {{ plantbuddy.title }}</h3>
    <form action="{% url 'share:delete_post' plantbuddy.id %}" method="post" style="text-align: center;">
        {% csrf_token %}
         <button class="button is-danger is-outlined is-fullwidth" type="submit" name="delete" value="Delete">Delete</button>&nbsp;
         <br><br>
    </form>
  </div>
</body>
</html>


{% endblock %}

share/templates/share/farmer_posts.html
{% extends "share/dashboard.html" %}
{% block posts %}
<div class="columns">
    <div class="column">

      {% if error %}
        <h3 class="title is-3" style="color: red">{{ error }}</h3>
      {% endif %}

        <h2 class="title is-2">Posts created by
          <span style="color:#1496ed">{{ user.username }}</span>:
        </h2>
        <!-- Page Content -->
        <div class="container">

          <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">
      {% for p in all_posts %}
              <!-- Blog Post -->
              <div class="card mb-4">
                <div class="card-body">
                  <h2 class="card-title">{{ p.title }}</h2>
                  <p class="card-text">{{ p.description }}</p>

                  <a href="{% url 'share:show_posts' p.id %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                  {{ p.created }}
                </div>
              </div>
      {% endfor %}
            </div>


          </div>

        </div>
          <!-- /.row -->

  </div>
      <br><br>
</div>



{% endblock %}

share/templates/share/index.html
{% extends "share/base.html" %}
{% block content %}

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-10">

        <h1 class="my-4" style="color: rgb(214, 121, 0);">plantBUDS Blog</h1>

{% for p in all_posts %}
        <!-- Blog Post -->
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">{{ p.title }}</h2>
            <p class="card-text">{{ p.description }}</p>

            <a href="{% url 'share:show_posts_index' p.id %}" class="btn btn-primary">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            {{ p.created }}
            <a href="#">{{ p.plantbuddy.user.username }}</a>
          </div>
        </div>
{% endfor %}
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item disabled">
            <a class="page-link" href="#">&larr;Newer </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">Older&rarr; </a>
          </li>
        </ul>
      </div>
      </div>
    </div>
    <!-- /.row -->
{% endblock %}

share/templates/share/info_page.html
{% extends "share/base.html" %}
{% block content %}

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="/static/share/images/farm.jpg" alt="icon">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Farmers and Gardeners!</h2>
          <p>Learn different techniques or way to plant different plants and veggies!</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="/static/share/images/plant.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Trade seeds!</h2>
          <p>Trade seeds with friends or have a gardening party to hang out and plants and trade seeds!</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="/static/share/images/veggies.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Garden party!</h2>
          <p>Plan a garden party within your community and gain knowledge on other peoples favorite types of seeds or just plant for fun!</p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

share/templates/share/login.html
{% extends "share/base.html" %}

{% block content %}
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Login</h5>
            <form class="form-login" action="{% url 'share:loguser' %}" method="post">
              {% csrf_token %}
              <div class="form-label-group">
                <input type="username" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus/>
                <label for="username">Username</label>
              </div>

              <div class="form-label-group">
                <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required/>
                <label for="inputPassword">Password</label>
              </div>

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember password</label>
              </div>
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Login</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock content%}

share/templates/share/publish_post.html
{% extends "share/dashboard.html" %}
{% block posts %}
<!DOCTYPE html>
<html>
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  body {font-family: Arial, Helvetica, sans-serif;}
  * {box-sizing: border-box;}

  h3 {
    text-align: center;
  }

  input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
  }

  input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }

  .container {
    border-radius: 5px;
    padding: 20px;
  }
  </style>
</head>

<body>
  <br><br><br>
  <h3>Publish a Post</h3>

  <div class="container">
    {% if error %}
       <h3 style="color: red">{{ error }}</h3>
    {% endif %}

    <form action = "{% url 'share:create_post' %}" method="post">
      {% csrf_token %}

      <label for="title">Title</label>
      <input type="text" id="title" name="title" placeholder="Title">

      <label for="description">Description</label>
      <input type="text" id="description" name="description" placeholder="Description">

      <label for="body">Body</label>
      <textarea id="body" name="body" placeholder="Write something..." style="height:200px"></textarea>

      <label for="subject">Subject</label>
      <select id="subject" name="subject">
        <option value="farming">Farming</option>
        <option value="gardening">Gardening</option>
        <option value="general">General</option>
      </select>

      <label class="checkbox">
        <br>Do you want to make this post public?
        <input type="checkbox"  id="make_public" name="make_public" />
      </label>


      <div class="field" style="float: center;">
        <div class="control">
          <button class="button is-success is-outlined is-fullwidth" type="submit" value="Publish">Publish</button>&nbsp;
        </div>
      </div>
    </form>
  </div>

</body>
</html>

{% endblock %}

share/templates/share/show_posts.html
{% extends "share/dashboard.html" %}
{% block posts %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog Post</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/blog-post.css" rel="stylesheet">

</head>

<body>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ posts.title }}</h1>

        <!-- description -->
        <h3 class='mt-4'> {{ posts.description }} </h3>

        <!-- subject -->
        <p class="lead">
          Subject:
          <a href="#">{{ posts.subject }} </a>
        </p>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{ posts.plantbuddy.user.username }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p> {{  posts.created }} </p>

        <hr>

        <!-- Post Content -->
        <p class="lead"> {{ posts.body }} </p>

        <hr>
        {% if user.id == posts.plantbuddy.user.id  %}
          <a class="button is-primary is-medium"
             href="{% url 'share:edit_post' posts.id %}" >Make changes to this post</a>
        {% endif %}
        <br><br>
        <br><br>

      </div>
    </div>
  </div>
  <!-- /.container -->
</body>

</html>

{% endblock %}

share/templates/share/signup.html
{% extends 'share/base.html' %}

{% block content %}
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign Up</h5>
            <form class="form-signup" action="{% url 'share:create' %}" method="post">
              {% csrf_token %}
              <div class="form-label-group">
                <input type="username" id="inputUsername" name="username" class="form-control" placeholder="Username" required autofocus/>
                <label for="inputUsername">Username</label>
              </div>
              <div class="form-label-group">
                <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email" required autofocus/>
                <label for="inputEmail">Email</label>
              </div>

              <div class="form-label-group">
                <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required/>
                <label for="inputPassword">Password</label>
              </div>

              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign up</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock content %}